# Generated by Django 5.0 on 2023-12-27 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album_name', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('Rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('musicians', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Musician.musicianmodel')),
            ],
        ),
    ]
